spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    alicloud:
      access-key: LTAI4G2ojCzb9bTC2CdDK1j8
      secret-key: r75KEHZNDykKSRABQvuBJFMMCGb0jg
      oss:
        endpoint: oss-cn-shenzhen.aliyuncs.com
  application:
    name: gulimall-third-party

server:
  port: 30000