spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    alicloud:
      access-key: LTAI4G6sF9bLVPj6dD7X1AfL
      secret-key: MJok4zr7y3J4AlhdstQlGnRZmSopj7
      oss:
        endpoint: oss-cn-shenzhen.aliyuncs.com
  application:
    name: gulimall-third-party

server:
  port: 30000

